#!/bin/sh
cd "${0%/*}" || exit                                # run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication snappyHexMesh -overwrite

# for parallel execution
runApplication decomposePar

# running the solver in parallel using mpirun
runParallel $(getApplication)

# reconstructing the case after parallel run
runApplication reconstructPar

#------------------------------------------------------------------------------
